.TH QUICKDCP 1 "July 2015" "1.0.0"

.SH NAME
QuickDCP - Le couteau suisse du projectionniste moderne, dans une interface graphique GTK+.

.SH SYNOPSIS
.B quickdcp [options]

.SH DESCRIPTION
.br
.P
What QuickDCP does and does not.
.br
.P
By default, Deluge will run in 'Classic' mode where the daemon functionality will be hidden and the GtkUI will automatically launch a 'deluged' process.  You can turn this off in the Preferences dialog.

.SH OPTIONS
.TP
.I [torrent]
List of ".torrent" files to add to the download queue.
.TP
.I -h, --help
Show this help message and exit.
.TP
.I -v, --version
Show program's version number and exit.
.TP
.I -V, --verbose
Output verbose runtime information about what QuickDCP is doing.
.TP
.I -l LOGFILE, --logfile=LOGFILE
Output to designated logfile instead of stdout
.TP
.I -L LOGLEVEL, --loglevel=LOGLEVEL
Set the log level (default is error): none, info, warning, error, critical, debug

.SH SEE ALSO
.B Homepage:
https://github.com/zanobox/quickdcp/

.SH AUTHOR
This manual page was written by Zanobox <zano@zanobox.net>.
.br
Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 3 or any later version published by the Free Software Foundation
.br
