# - Try to find libASDCP
# Once done, this will define
#
#  ASDCP_FOUND - system has asdcplib
#  ASDCP_INCLUDE_DIRS - the asdcplib include directories
#  ASDCP_LIBRARIES - link these to use asdcplib

# Include dir
FIND_PATH(ASDCP_INCLUDE_DIR
  NAMES AS_DCP.h
  PATHS
	${INSTALL_PREFIX}/include
	${STATIC_LIBS_DIR}/include
  PATH_SUFFIXES
	qdcp-asdcp
   NO_DEFAULT_PATH
)

FIND_PATH(KUMU_INCLUDE_DIR
  NAMES KM_error.h
  PATHS
	${INSTALL_PREFIX}/include
	${STATIC_LIBS_DIR}/include
  PATH_SUFFIXES
	qdcp-asdcp
   NO_DEFAULT_PATH
)

FIND_PATH(AS02_INCLUDE_DIR
  NAMES AS_02.h
  PATHS
	${INSTALL_PREFIX}/include
	${STATIC_LIBS_DIR}/include
  PATH_SUFFIXES
	qdcp-asdcp
   NO_DEFAULT_PATH
)


# Finally the library itself
FIND_LIBRARY(ASDCP_LIBRARY
  NAMES asdcp
  PATHS
	${INSTALL_PREFIX}/lib
	${STATIC_LIBS_DIR}/lib
  PATH_SUFFIXES
	qdcp-asdcp
	qdcp-asdcp/lib
  NO_DEFAULT_PATH
)
FIND_LIBRARY(KUMU_LIBRARY
  NAMES kumu
  PATHS
	${INSTALL_PREFIX}/lib
	${STATIC_LIBS_DIR}/lib
  PATH_SUFFIXES
	qdcp-asdcp
	qdcp-asdcp/lib
  NO_DEFAULT_PATH
)
FIND_LIBRARY(AS02_LIBRARY
  NAMES as02
  PATHS
	${INSTALL_PREFIX}/lib
	${STATIC_LIBS_DIR}/lib
  PATH_SUFFIXES
	qdcp-asdcp
	qdcp-asdcp/lib
  NO_DEFAULT_PATH
)

MESSAGE("ASDCP_INCLUDE_DIR : ${ASDCP_INCLUDE_DIR}")
MESSAGE("KUMU_INCLUDE_DIR  : ${KUMU_INCLUDE_DIR}")
MESSAGE("AS02_INCLUDE_DIR  : ${AS02_INCLUDE_DIR}")

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(ASDCP DEFAULT_MSG ASDCP_LIBRARY ASDCP_INCLUDE_DIR)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(KUMU DEFAULT_MSG KUMU_LIBRARY KUMU_INCLUDE_DIR)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(AS02 DEFAULT_MSG AS02_LIBRARY AS02_INCLUDE_DIR)


IF(ASDCP_FOUND AND KUMU_FOUND)
	SET(ASDCP_LIBRARIES ${AS02_LIBRARY} ${ASDCP_LIBRARY} ${KUMU_LIBRARY})
	SET(ASDCP_INCLUDE_DIRS ${ASDCP_INCLUDE_DIR} ${KUMU_INCLUDE_DIR} ${AS02_INCLUDE_DIR})
	MESSAGE(GREEN "ASDCP_LIBRARY : ${White}${ASDCP_LIBRARY}")
	MESSAGE(GREEN "AS02_LIBRARY  : ${White}${AS02_LIBRARY}")
	MESSAGE(GREEN "KUMU_LIBRARY  : ${White}${KUMU_LIBRARY}")
	MESSAGE(GREEN "Includes      : ${White}${ASDCP_INCLUDE_DIR}")
	
ELSE(ASDCP_FOUND AND KUMU_FOUND)
	SET(ASDCP_FOUND, 0)
	SET(KUMU_FOUND, 0)
	
ENDIF(ASDCP_FOUND AND KUMU_FOUND)

