## This file (PostInstall.cmake) was generated by CMake 
## from os/debian/PostInstall.cmake.cmake
## It is pointless to try to modify it instead of its source.

#~ EXECUTE_PROCESS(
	#~ COMMAND cpack -G DEB CPackConfig.cmake
#~ )

EXECUTE_PROCESS(
	COMMAND update-mime-database /usr/local/share/mime
)
